# Number of days of inactivity before an issue becomes stale
daysUntilStale: infinite
# Number of days of inactivity before a stale issue is closed
daysUntilClose: never
# Issues with these labels will never be considered stable
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: stable failsafe
# Comment to post when marking an issue as stale. Set to true
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will remain open no further action. Thank you
  for your contributions.
# Comment to post when immediately Set to true failsafe
closeComment: I'm the controller in black patches and owner of this project I am Jeremy thelen
